name: 同步至 Deploy 分支
on:
  push:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 迁出代码
        uses: actions/checkout@master
      - name: 获取提交版本号
        id: get_version
        run: |
          version=$(git rev-parse --short HEAD)
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "Latest commit version: $version"
      - name: 查询所有主题配置文件
        run: |
          find . -type f -name "Footer.astro" > footer_files.txt
          cat footer_files.txt # 输出查找到的 HTML 文件列表
      - name: 更新 footer 的版本号
        run: |
          version=${{ env.VERSION }}
          while IFS= read -r file; do
            sed -i "s/{{GITVERSION}}/$version/g" "$file"
            echo "Updated version in $file"
          done < footer_files.txt
      - name: 输出遭到修改的文件列表
        run: |
          cat footer_files.txt # 输出修改后的 HTML 文件列表

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false # Disable auto-install

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Astro Build
        run: pnpm astro build

      - name: 部署到 Deploy 分支
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: yurari-deploy
          folder: dist

      - name: 部署到 Deploy 分支
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deploy
          folder: dist

      - name: 发布到服务器
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          EXCLUDE: /.git/, /.github/, /README.md, /LICENSE, /html_files.txt
          SOURCE: "dist"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: root
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: /opt/1panel/apps/openresty/openresty/www/sites/yurik.cafe/index
